run_name: ddim
seed: 42
data_dir: /content/data/imagenet100_128x128/train
data_valid: /content/data/imagenet100_128x128/validation


image_size: 64
batch_size: 256
num_workers: 10
num_classes: 100
num_epochs: 300

learning_rate: 2e-4
weight_decay: 1e-4
num_train_timesteps: 1000
num_inference_steps: 100
beta_start: 0.0001
beta_end: 0.01
beta_schedule: 'linear'

variance_type: fixed_small
prediction_type: epsilon
clip_sample: True
clip_sample_range: 1.0

unet_in_size: 32
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0

latent_ddpm: True
use_cfg: True
use_ddim: True
use_vae: True

cfg_guidance_scale: 2.0

mixed_precision: fp16