run_name: ddim_15classes_cosine_ema_resume
seed: 43
data_dir: /content/data/imagenet100_128x128/train
data_valid: /content/data/imagenet100_128x128/validation


image_size: 128
batch_size: 256
num_workers: 10
num_classes: 15
num_epochs: 500

learning_rate: 2e-4
weight_decay: 1e-4
num_train_timesteps: 1000
num_inference_steps: 250
beta_start: 0.0001
beta_end: 0.02
beta_schedule: 'cosine'

variance_type: fixed_small
prediction_type: epsilon
clip_sample: True
clip_sample_range: 1.0

unet_in_size: 32
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0

latent_ddpm: True
use_cfg: True
use_ddim: True
use_vae: True
use_ema: True

resume: True
resume_ckpt: "/content/gdrive/MyDrive/11685 Deep Learning/11685 Diffusion Probabilistic Models/hw5_student_starter_code/experiments/exp-13-ddim_15classes_cosine_ema/checkpoints/checkpoint_epoch_last.pth"

cfg_guidance_scale: 3.0

mixed_precision: fp16